/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as PayOrderIdRouteImport } from './routes/pay.$orderId'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as AdminShippingRouteImport } from './routes/admin.shipping'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInvoiceRouteImport } from './routes/admin.invoice'
import { Route as AdminCountriesRouteImport } from './routes/admin.countries'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangCheckoutRouteImport } from './routes/$lang.checkout'
import { Route as LangCartRouteImport } from './routes/$lang.cart'
import { Route as LangAuthRouteImport } from './routes/$lang.auth'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangProductsIndexRouteImport } from './routes/$lang.products.index'
import { Route as LangOrdersIndexRouteImport } from './routes/$lang.orders.index'
import { Route as LangProductsSlugRouteImport } from './routes/$lang.products.$slug'
import { Route as LangPayOrderIdRouteImport } from './routes/$lang.pay.$orderId'
import { Route as LangOrdersIdRouteImport } from './routes/$lang.orders.$id'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PayOrderIdRoute = PayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoiceRoute = AdminInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCountriesRoute = AdminCountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => AdminRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangCheckoutRoute = LangCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LangRoute,
} as any)
const LangCartRoute = LangCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthRoute = LangAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangProductsIndexRoute = LangProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LangRoute,
} as any)
const LangOrdersIndexRoute = LangOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => LangRoute,
} as any)
const LangProductsSlugRoute = LangProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangPayOrderIdRoute = LangPayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => LangRoute,
} as any)
const LangOrdersIdRoute = LangOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/cart': typeof LangCartRoute
  '/$lang/checkout': typeof LangCheckoutRoute
  '/$lang/contact': typeof LangContactRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/invoice': typeof AdminInvoiceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/$lang/orders/$id': typeof LangOrdersIdRoute
  '/$lang/pay/$orderId': typeof LangPayOrderIdRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/orders/': typeof LangOrdersIndexRoute
  '/$lang/products/': typeof LangProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/cart': typeof LangCartRoute
  '/$lang/checkout': typeof LangCheckoutRoute
  '/$lang/contact': typeof LangContactRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/invoice': typeof AdminInvoiceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/$lang': typeof LangIndexRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/$lang/orders/$id': typeof LangOrdersIdRoute
  '/$lang/pay/$orderId': typeof LangPayOrderIdRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/orders': typeof LangOrdersIndexRoute
  '/$lang/products': typeof LangProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/cart': typeof LangCartRoute
  '/$lang/checkout': typeof LangCheckoutRoute
  '/$lang/contact': typeof LangContactRoute
  '/admin/countries': typeof AdminCountriesRoute
  '/admin/invoice': typeof AdminInvoiceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/$lang/orders/$id': typeof LangOrdersIdRoute
  '/$lang/pay/$orderId': typeof LangPayOrderIdRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/orders/': typeof LangOrdersIndexRoute
  '/$lang/products/': typeof LangProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/about'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/$lang/about'
    | '/$lang/auth'
    | '/$lang/cart'
    | '/$lang/checkout'
    | '/$lang/contact'
    | '/admin/countries'
    | '/admin/invoice'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/shipping'
    | '/orders/$id'
    | '/pay/$orderId'
    | '/products/$slug'
    | '/$lang/'
    | '/admin/'
    | '/orders/'
    | '/products/'
    | '/$lang/orders/$id'
    | '/$lang/pay/$orderId'
    | '/$lang/products/$slug'
    | '/$lang/orders/'
    | '/$lang/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/$lang/about'
    | '/$lang/auth'
    | '/$lang/cart'
    | '/$lang/checkout'
    | '/$lang/contact'
    | '/admin/countries'
    | '/admin/invoice'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/shipping'
    | '/orders/$id'
    | '/pay/$orderId'
    | '/products/$slug'
    | '/$lang'
    | '/admin'
    | '/orders'
    | '/products'
    | '/$lang/orders/$id'
    | '/$lang/pay/$orderId'
    | '/$lang/products/$slug'
    | '/$lang/orders'
    | '/$lang/products'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/about'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/$lang/about'
    | '/$lang/auth'
    | '/$lang/cart'
    | '/$lang/checkout'
    | '/$lang/contact'
    | '/admin/countries'
    | '/admin/invoice'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/quotes'
    | '/admin/shipping'
    | '/orders/$id'
    | '/pay/$orderId'
    | '/products/$slug'
    | '/$lang/'
    | '/admin/'
    | '/orders/'
    | '/products/'
    | '/$lang/orders/$id'
    | '/$lang/pay/$orderId'
    | '/$lang/products/$slug'
    | '/$lang/orders/'
    | '/$lang/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  OrdersIdRoute: typeof OrdersIdRoute
  PayOrderIdRoute: typeof PayOrderIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$orderId': {
      id: '/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/pay/$orderId'
      preLoaderRoute: typeof PayOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoice': {
      id: '/admin/invoice'
      path: '/invoice'
      fullPath: '/admin/invoice'
      preLoaderRoute: typeof AdminInvoiceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/countries': {
      id: '/admin/countries'
      path: '/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof AdminCountriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/checkout': {
      id: '/$lang/checkout'
      path: '/checkout'
      fullPath: '/$lang/checkout'
      preLoaderRoute: typeof LangCheckoutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/cart': {
      id: '/$lang/cart'
      path: '/cart'
      fullPath: '/$lang/cart'
      preLoaderRoute: typeof LangCartRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/auth': {
      id: '/$lang/auth'
      path: '/auth'
      fullPath: '/$lang/auth'
      preLoaderRoute: typeof LangAuthRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/products/': {
      id: '/$lang/products/'
      path: '/products'
      fullPath: '/$lang/products/'
      preLoaderRoute: typeof LangProductsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/orders/': {
      id: '/$lang/orders/'
      path: '/orders'
      fullPath: '/$lang/orders/'
      preLoaderRoute: typeof LangOrdersIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/products/$slug': {
      id: '/$lang/products/$slug'
      path: '/products/$slug'
      fullPath: '/$lang/products/$slug'
      preLoaderRoute: typeof LangProductsSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/pay/$orderId': {
      id: '/$lang/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/$lang/pay/$orderId'
      preLoaderRoute: typeof LangPayOrderIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/orders/$id': {
      id: '/$lang/orders/$id'
      path: '/orders/$id'
      fullPath: '/$lang/orders/$id'
      preLoaderRoute: typeof LangOrdersIdRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangAuthRoute: typeof LangAuthRoute
  LangCartRoute: typeof LangCartRoute
  LangCheckoutRoute: typeof LangCheckoutRoute
  LangContactRoute: typeof LangContactRoute
  LangIndexRoute: typeof LangIndexRoute
  LangOrdersIdRoute: typeof LangOrdersIdRoute
  LangPayOrderIdRoute: typeof LangPayOrderIdRoute
  LangProductsSlugRoute: typeof LangProductsSlugRoute
  LangOrdersIndexRoute: typeof LangOrdersIndexRoute
  LangProductsIndexRoute: typeof LangProductsIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangAuthRoute: LangAuthRoute,
  LangCartRoute: LangCartRoute,
  LangCheckoutRoute: LangCheckoutRoute,
  LangContactRoute: LangContactRoute,
  LangIndexRoute: LangIndexRoute,
  LangOrdersIdRoute: LangOrdersIdRoute,
  LangPayOrderIdRoute: LangPayOrderIdRoute,
  LangProductsSlugRoute: LangProductsSlugRoute,
  LangOrdersIndexRoute: LangOrdersIndexRoute,
  LangProductsIndexRoute: LangProductsIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface AdminRouteChildren {
  AdminCountriesRoute: typeof AdminCountriesRoute
  AdminInvoiceRoute: typeof AdminInvoiceRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCountriesRoute: AdminCountriesRoute,
  AdminInvoiceRoute: AdminInvoiceRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  OrdersIdRoute: OrdersIdRoute,
  PayOrderIdRoute: PayOrderIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
